name: Publish Release

on:
  release:
    types: [published]

jobs:

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "GitHub Container Registry Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Extract Metadata"
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: superepicstudios/srt-live

      - name: "Build & Push"
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{steps.metadata.outputs.tags}}
          labels: ${{steps.metadata.outputs.labels}}

      - name: Artifact Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          subject-digest: ${{steps.push.outputs.digest}}
          push-to-registry: true
